name = "voice-transcription-db"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "voice-transcription-db"
database_id = "3a4b216e-4a33-401c-8225-0f377ae1e149"

# For development/testing
[[d1_databases]]
binding = "DB_DEV"
database_name = "voice-transcription-db"
database_id = "3a4b216e-4a33-401c-8225-0f377ae1e149"