name = "voice-transcription-db"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "voice-transcription-prod"
database_id = "113aa2be-2de8-4cc5-9c66-9e413d1cc121"

# For development/testing
[[d1_databases]]
binding = "DB_DEV"
database_name = "voice-transcription-dev"
database_id = "dd1ef486-decf-4f5e-bf07-db9f2fedf072" 